from enum import Enum

class MarketProfile(str, Enum):
    SPOT = "SPOT"
    FUTURES = "FUTURES"

class ContractFamily(str, Enum):
    LINEAR = "LINEAR"
    INVERSE = "INVERSE"
    SPOT = "SPOT"

class ContractType(str, Enum):
    PERPETUAL = "PERPETUAL"
    DELIVERY_CURRENT = "DELIVERY_CURRENT"
    DELIVERY_NEXT = "DELIVERY_NEXT"
    OTHER = "OTHER"

class MarketType(str, Enum):
    SPOT = "SPOT"
    FUTURES_LINEAR = "FUTURES_LINEAR"
    FUTURES_INVERSE = "FUTURES_INVERSE"

class QualityState(str, Enum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    STALE = "STALE"
    DISCONNECTED = "DISCONNECTED"
    INVALID = "INVALID"

class TransportState(str, Enum):
    WEBSOCKET = "WEBSOCKET"
    DEGRADED = "DEGRADED"
    RECOVERING = "RECOVERING"
    DISCONNECTED = "DISCONNECTED"

class SignalState(str, Enum):
    DISCOVERED = "DISCOVERED"
    QUALIFIED = "QUALIFIED"
    ARMED = "ARMED"
    TRIGGERED = "TRIGGERED"
    EXECUTED = "EXECUTED"
    REJECTED = "REJECTED"
    BLOCKED = "BLOCKED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"
    INVALIDATED = "INVALIDATED"

class OrderState(str, Enum):
    NEW = "NEW"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELED = "CANCELED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    PENDING_SUBMIT = "PENDING_SUBMIT"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    UNKNOWN = "UNKNOWN"

class PositionState(str, Enum):
    PENDING_ENTRY = "PENDING_ENTRY"
    OPEN = "OPEN"
    REDUCED = "REDUCED"
    TRAILING = "TRAILING"
    CLOSING = "CLOSING"
    CLOSED = "CLOSED"
    POSITION_DATA_BLIND = "POSITION_DATA_BLIND"  # FBK-05

class TrendRegime(str, Enum):
    TRENDING_UP = "TRENDING_UP"
    TRENDING_DOWN = "TRENDING_DOWN"
    RANGING = "RANGING"
    UNCERTAIN = "UNCERTAIN"

class VolRegime(str, Enum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"

class Bias(str, Enum):
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"
    UNDEFINED = "UNDEFINED"

class Direction(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"

class GateReason(str, Enum):
    DATA_STALE = "DATA_STALE"
    DATA_DISCONNECTED = "DATA_DISCONNECTED"
    ORDERBOOK_STALE = "ORDERBOOK_STALE"
    CANDLE_DATA_INVALID = "CANDLE_DATA_INVALID"
    CLOCK_DRIFT = "CLOCK_DRIFT"
    MARKET_DATA_DISCREPANCY = "MARKET_DATA_DISCREPANCY"
    INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"
    SYMBOL_INVALID = "SYMBOL_INVALID"
    CONTRACT_NOT_TRADING = "CONTRACT_NOT_TRADING"
    CONTRACT_SETTLING = "CONTRACT_SETTLING"
    UNIVERSE_WARMING_UP = "UNIVERSE_WARMING_UP"
    LIQUIDITY_TOO_LOW = "LIQUIDITY_TOO_LOW"
    SPREAD_TOO_WIDE = "SPREAD_TOO_WIDE"
    FUNDING_TOO_COSTLY = "FUNDING_TOO_COSTLY"
    LIQUIDATION_BUFFER_INSUFFICIENT = "LIQUIDATION_BUFFER_INSUFFICIENT"
    LEVERAGE_EXCEEDS_CAP = "LEVERAGE_EXCEEDS_CAP"
    POSITION_DATA_BLIND = "POSITION_DATA_BLIND"
    VENUE_SWITCH_INVALIDATED = "VENUE_SWITCH_INVALIDATED"
    NO_DERIVS_CONTEXT = "NO_DERIVS_CONTEXT"
    MARKET_TYPE_VIOLATION = "MARKET_TYPE_VIOLATION"
    INVALID_STRUCTURE = "INVALID_STRUCTURE"
    NO_CLEAR_ENTRY = "NO_CLEAR_ENTRY"
    NO_CLEAR_TARGET = "NO_CLEAR_TARGET"
    INSUFFICIENT_RR = "INSUFFICIENT_RR"
    COST_TOO_HIGH = "COST_TOO_HIGH"
    MARKET_REGIME_INCOMPATIBLE = "MARKET_REGIME_INCOMPATIBLE"
    CONFLICTING_EVIDENCE = "CONFLICTING_EVIDENCE"
    HTF_LTF_CONFLICT = "HTF_LTF_CONFLICT"
    SESSION_INACTIVE = "SESSION_INACTIVE"
    NEWS_RISK = "NEWS_RISK"
    NEWS_UNAVAILABLE = "NEWS_UNAVAILABLE"
    STRATEGY_DISABLED = "STRATEGY_DISABLED"
    EXECUTION_UNSAFE = "EXECUTION_UNSAFE"
    RISK_LIMIT = "RISK_LIMIT"
    COOLDOWN_ACTIVE = "COOLDOWN_ACTIVE"
    DUPLICATE_SETUP = "DUPLICATE_SETUP"
    KILL_SWITCH_ACTIVE = "KILL_SWITCH_ACTIVE"
    RECONCILIATION_ERROR = "RECONCILIATION_ERROR"
    SIGNAL_EXPIRED = "SIGNAL_EXPIRED"
    INSUFFICIENT_PROBABILITY_DATA = "INSUFFICIENT_PROBABILITY_DATA"
    INSUFFICIENT_SAMPLE = "INSUFFICIENT_SAMPLE"
    NOT_BACKTESTABLE_WITH_AVAILABLE_DATA = "NOT_BACKTESTABLE_WITH_AVAILABLE_DATA"
    EXCLUDED_ASSET_CLASS = "EXCLUDED_ASSET_CLASS"
    NOT_TRADING = "NOT_TRADING"
    EXCLUDED_BY_OPERATOR = "EXCLUDED_BY_OPERATOR"
    WARMING_UP = "WARMING_UP"
    NOT_SUBSCRIBED = "NOT_SUBSCRIBED"

class AppMode(str, Enum):
    RESEARCH = "RESEARCH"
    PAPER = "PAPER"
    LIVE = "LIVE"

class ProbabilityStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    INSUFFICIENT_SAMPLE = "INSUFFICIENT_SAMPLE"
    UNCALIBRATED = "UNCALIBRATED"
    NO_OOS_VALIDATION = "NO_OOS_VALIDATION"
    VERSION_MISMATCH = "VERSION_MISMATCH"
    DRIFT_DEGRADED = "DRIFT_DEGRADED"
    NOT_REQUIRED = "NOT_REQUIRED"

class AssetClass(str, Enum):
    CRYPTO = "CRYPTO"
    TRADFI = "TRADFI"
    UNKNOWN = "UNKNOWN"
