"""001_baseline

Revision ID: 001
Revises: 
Create Date: 2026-09-21 17:25:30.387485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_segments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('contract', sa.String(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('range_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('range_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('high', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('low', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('close', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('volume', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('quote_volume', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('taker_buy_volume', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('ingestion_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue', 'symbol', 'timeframe', 'open_time', name='uq_candle_venue_symbol_tf_open')
    )
    op.create_index('ix_candle_symbol_tf_close', 'candles', ['symbol', 'timeframe', 'close_time'], unique=False)
    op.create_index(op.f('ix_candles_open_time'), 'candles', ['open_time'], unique=False)
    op.create_index(op.f('ix_candles_symbol'), 'candles', ['symbol'], unique=False)
    op.create_index(op.f('ix_candles_timeframe'), 'candles', ['timeframe'], unique=False)
    op.create_index(op.f('ix_candles_venue'), 'candles', ['venue'], unique=False)
    op.create_table('command_results',
    sa.Column('command_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('command_id')
    )
    op.create_table('commands',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('config_versions',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('consumer_cursors',
    sa.Column('consumer', sa.String(), nullable=False),
    sa.Column('last_event_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('consumer')
    )
    op.create_table('contract_registry',
    sa.Column('contract_id', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('base', sa.String(), nullable=False),
    sa.Column('quote', sa.String(), nullable=False),
    sa.Column('settle_asset', sa.String(), nullable=True),
    sa.Column('contract_family', sa.String(), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('contract_multiplier', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('tick_size', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('step_size', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('min_notional', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('max_leverage', sa.Integer(), nullable=True),
    sa.Column('margin_asset', sa.String(), nullable=True),
    sa.Column('funding_interval_h', sa.Integer(), nullable=True),
    sa.Column('asset_class', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('onboard_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('contract_id')
    )
    op.create_index(op.f('ix_contract_registry_symbol'), 'contract_registry', ['symbol'], unique=False)
    op.create_index(op.f('ix_contract_registry_venue'), 'contract_registry', ['venue'], unique=False)
    op.create_table('contract_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.String(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_status_history_contract_id'), 'contract_status_history', ['contract_id'], unique=False)
    op.create_table('coverage_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('listed', sa.Integer(), nullable=False),
    sa.Column('analysable', sa.Integer(), nullable=False),
    sa.Column('analysed_live', sa.Integer(), nullable=False),
    sa.Column('warming_up', sa.Integer(), nullable=False),
    sa.Column('excluded', sa.Integer(), nullable=False),
    sa.Column('not_subscribed', sa.Integer(), nullable=False),
    sa.Column('stale', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_risk_state',
    sa.Column('risk_day', sa.String(), nullable=False),
    sa.Column('starting_equity', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('current_equity', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('daily_loss', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('daily_realized_pnl', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('trades_today', sa.Integer(), nullable=False),
    sa.Column('risk_lock', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('risk_day')
    )
    op.create_table('event_outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_intents',
    sa.Column('intent_id', sa.String(), nullable=False),
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('entry', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('stop', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('margin', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('liquidation_price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('intent_id')
    )
    op.create_table('funding_rates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('funding_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_rates_symbol'), 'funding_rates', ['symbol'], unique=False)
    op.create_index(op.f('ix_funding_rates_venue'), 'funding_rates', ['venue'], unique=False)
    op.create_table('kill_switch_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('latest_quotes',
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('bid', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('ask', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('mark_price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('margin_tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('notional_cap', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('maintenance_margin_rate', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('cum', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('max_leverage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mark_prices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('mark', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('index_price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mark_prices_symbol'), 'mark_prices', ['symbol'], unique=False)
    op.create_index(op.f('ix_mark_prices_venue'), 'mark_prices', ['venue'], unique=False)
    op.create_table('open_interest',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('oi', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('oi_usd', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_open_interest_symbol'), 'open_interest', ['symbol'], unique=False)
    op.create_index(op.f('ix_open_interest_venue'), 'open_interest', ['venue'], unique=False)
    op.create_table('paper_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('equity', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('cash', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('peak_equity', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('fees_paid', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('funding_paid', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('mark_price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('liquidation_price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('margin', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('take_profit_1', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('take_profit_2', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('fees', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('funding', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_table('provider_status',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('capability', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('throttled_requests', sa.Integer(), nullable=False),
    sa.Column('data_age_s', sa.Integer(), nullable=True),
    sa.Column('circuit_state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('checkpoint', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('signal_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('previous_state', sa.String(), nullable=True),
    sa.Column('new_state', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_events_signal_id'), 'signal_events', ['signal_id'], unique=False)
    op.create_table('signal_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('net_r', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('would_be_blocked_by_risk', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_outcomes_signal_id'), 'signal_outcomes', ['signal_id'], unique=True)
    op.create_table('signals',
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('contract_family', sa.String(), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('market_type', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('primary_timeframe', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('setup_score', sa.Integer(), nullable=True),
    sa.Column('setup_quality', sa.String(), nullable=True),
    sa.Column('probability', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('probability_status', sa.String(), nullable=True),
    sa.Column('expected_r', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('entry', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('stop', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('target_1', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('target_2', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('regime', sa.String(), nullable=True),
    sa.Column('session', sa.String(), nullable=True),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('evidence_hash', sa.String(), nullable=True),
    sa.Column('analysis_version', sa.String(), nullable=True),
    sa.Column('config_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_table('source_switch_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('capability', sa.String(), nullable=False),
    sa.Column('from_source', sa.String(), nullable=True),
    sa.Column('to_source', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_health',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metrics_metric'), 'system_metrics', ['metric'], unique=False)
    op.create_table('universe_registry',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('base', sa.String(), nullable=False),
    sa.Column('quote', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tick_size', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('step_size', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('min_notional', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('market_type', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('venue_status',
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('venue')
    )
    op.create_table('worker_state',
    sa.Column('process', sa.String(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('queue_depth', sa.Integer(), nullable=True),
    sa.Column('lag_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('process')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_state')
    op.drop_table('venue_status')
    op.drop_table('universe_registry')
    op.drop_index(op.f('ix_system_metrics_metric'), table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_table('system_health')
    op.drop_table('source_switch_events')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_signal_outcomes_signal_id'), table_name='signal_outcomes')
    op.drop_table('signal_outcomes')
    op.drop_index(op.f('ix_signal_events_signal_id'), table_name='signal_events')
    op.drop_table('signal_events')
    op.drop_table('scan_jobs')
    op.drop_table('risk_events')
    op.drop_table('provider_status')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_table('positions')
    op.drop_table('paper_accounts')
    op.drop_index(op.f('ix_open_interest_venue'), table_name='open_interest')
    op.drop_index(op.f('ix_open_interest_symbol'), table_name='open_interest')
    op.drop_table('open_interest')
    op.drop_index(op.f('ix_mark_prices_venue'), table_name='mark_prices')
    op.drop_index(op.f('ix_mark_prices_symbol'), table_name='mark_prices')
    op.drop_table('mark_prices')
    op.drop_table('margin_tiers')
    op.drop_table('latest_quotes')
    op.drop_table('kill_switch_state')
    op.drop_index(op.f('ix_funding_rates_venue'), table_name='funding_rates')
    op.drop_index(op.f('ix_funding_rates_symbol'), table_name='funding_rates')
    op.drop_table('funding_rates')
    op.drop_table('execution_intents')
    op.drop_table('event_outbox')
    op.drop_table('daily_risk_state')
    op.drop_table('coverage_reports')
    op.drop_index(op.f('ix_contract_status_history_contract_id'), table_name='contract_status_history')
    op.drop_table('contract_status_history')
    op.drop_index(op.f('ix_contract_registry_venue'), table_name='contract_registry')
    op.drop_index(op.f('ix_contract_registry_symbol'), table_name='contract_registry')
    op.drop_table('contract_registry')
    op.drop_table('consumer_cursors')
    op.drop_table('config_versions')
    op.drop_table('commands')
    op.drop_table('command_results')
    op.drop_index(op.f('ix_candles_venue'), table_name='candles')
    op.drop_index(op.f('ix_candles_timeframe'), table_name='candles')
    op.drop_index(op.f('ix_candles_symbol'), table_name='candles')
    op.drop_index(op.f('ix_candles_open_time'), table_name='candles')
    op.drop_index('ix_candle_symbol_tf_close', table_name='candles')
    op.drop_table('candles')
    op.drop_table('archive_segments')
    # ### end Alembic commands ###
