"""Risk ports — domain interfaces, no sqlalchemy import."""

from typing import Protocol

class KillSwitchStore(Protocol):
    def is_active(self) -> bool: ...
    def activate(self, reason: str, mode: str = "BLOCK_NEW_TRADES"): ...
    def deactivate(self): ...
